ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        # GPS로부터 변환된 Odometry 데이터를 입력으로 사용
        odom0: /odometry/gps
        odom0_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]
        odom0_differential: false

navsat_transform_node:
    ros__parameters:
        frequency: 30.0
        magnetic_declination_radians: -0.155334 # 서울 기준 자기편각
        yaw_offset: 1.5707963                     # 90도 회전 (필요시 조정)
        zero_altitude: true
        publish_filtered_gps: true
        use_odometry_yaw: false
        wait_for_datum: true
        # ==========================================================
        # 중요: 실제 주행 시작점의 위도, 경도로 반드시 수정하세요!
        # 이 위치가 지역 좌표계의 원점(0, 0)이 됩니다.
        # 예: 서울 시청 근처
        datum: [37.5665, 126.9780, 0.0]
        # ==========================================================
